# Generated by Django 2.1.1 on 2020-09-11 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=300, upload_to='')),
                ('image_resize', models.ImageField(blank=True, default=None, max_length=300, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Image File',
                'db_table': 'portfolio_image_file',
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('template', models.CharField(max_length=1000)),
                ('data', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Layout',
                'db_table': 'portfolio_layout',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('data', models.TextField(default='{}')),
                ('layout', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Layout')),
            ],
            options={
                'verbose_name': 'Page',
                'db_table': 'portfolio_page',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('data', models.TextField(default='{}')),
                ('styles', models.TextField(default='{"style":[]}')),
                ('menu', models.BooleanField(default=True)),
                ('home', models.BooleanField(default=True)),
                ('link', models.CharField(default='#', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('layout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Layout')),
            ],
            options={
                'verbose_name': 'Section',
                'db_table': 'portfolio_section',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=300, upload_to='')),
                ('link', models.CharField(max_length=300)),
                ('alt', models.CharField(default='This', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Social Media',
                'db_table': 'portfolio_social_media',
            },
        ),
        migrations.CreateModel(
            name='TextBody',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Section')),
            ],
            options={
                'verbose_name': 'Text Body',
                'db_table': 'portfolio_text_body',
            },
        ),
        migrations.AddField(
            model_name='imagefile',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Section'),
        ),
    ]
